// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DeleteDialog(arg1:number):Promise<void>;

export function GetDialogs():Promise<Array<main.Dialog>>;

export function GetMessages(arg1:number):Promise<Array<main.Message>>;

export function SendMessage(arg1:number,arg2:string):Promise<main.SendResp>;
